### ISSUE TITLE
AttributeError: 'module' object has no attribute 'BluetoothSocket'

### ISSUE THREAD

**Issue by icepick3000** [derHeinz/divoom-adapter#14]
Hi,

When i run the code i get;

Traceback (most recent call last):
  File "show-time.py", line 17, in <module>
    dev = divoom_device.DivoomDevice(DIVOMM_ADR)
  File "/icepick/divoom/divoom-adapter/divoom_device.py", line 6, in __init__
    self.sock = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
AttributeError: 'module' object has no attribute 'BluetoothSocket'

However I do have python-bluez installed;

root@raspberrypi:/icepick/divoom/divoom-adapter# apt-get install python-bluez
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-bluez is already the newest version (0.22+really0.22-1).
0 upgraded, 0 newly installed, 0 to remove and 63 not upgraded.

Any ideas? I am running python 2.7

**Comment by icepick3000** [comment]
When I did python -m pip uninstall pybluez I got rid of this error.
